# This file controls the settings for your Quarto template from www.marvinschmitt.com

# website settings
website:
  title: "Olaf Borghi" # Your name
  description: "MSCA Early Stage Researcher"  # A brief slogan (optional)
  image: img/my_image.jpg
  
  favicon: img/favicon.png
  
  # start of the navigation bar at the top of the website
  navbar:
    pinned: true
    logo: /img/logo.png
    
    # your sub-pages
    left:
      - text: "Publications"
        href: publications/index.qmd
      - text: "Blog Posts"
        href: blog/index.qmd
      - text: "CV"
        href: cv/index.qmd
    
    # your social media handles
    right:
      - icon: folder-symlink
        href: https://www.olafborghi.com
      - icon: twitter
        href: https://twitter.com/olafborghi
      - icon: github
        href: https://github.com/olafborghi
      - icon: envelope
        aria-label: email
        href: "mailto:olaf.borghi@rhul.ac.uk"  
  
  

# Don't touch unless you know what you are doing :) ------------
  search: 
    location: navbar
    type: textbox
  page-footer: 
    left: |
      <span class="faux-block">&#169; 2024 Olaf Borghi CC BY-SA 4.0</span>
    center: |
      <span class="faux-block"><a href="https://www.marvinschmitt.com/blog/website-tutorial-quarto/">This website is based on this very helpful tutorial</a></span>
    right: |
      <span class="faux-block"><a href="https://github.com/olafborghi/olafborghi.github.io/">View source on GitHub</a></span>

project:
  type: website
  output-dir: docs

  preview: 
    port: 22222
    browser: true
    watch-inputs: true
    navigate: true

execute:
  freeze: true

format:
  html:
    fontsize: 1.1em
    theme: 
      - pulse
      - html/styles.scss
    toc: false
    code-link: true
    anchor-sections: true
    fig-cap-location: margin
    reference-location: margin
    footnotes-hover: true