---
title: "Publications"
---

My work related to my PhD project and the politics of adolescence is yet to be published. You can find some of my previous published work from my time as a BSc and MSc student at the university of Vienna below. For a full list of my past and current projects, please refer to my [CV](../cv).

----

## Day-to-Day Associations between Mindfulness and Perceived Stress: Insights from Random Intercept Cross-Lagged Panel Modeling

**Authors:** Olaf Borghi, Martin Voracek, Ulrich S. Tran

**Open data & code:** [Link to OSF](https://osf.io/7tnwq/?view_only=be9770d36cd245dcacee84c9ce8b600d)

This work is currently in the final stage of review. 

::: {.callout-note}
## Abstract

**Objective:** Mindfulness is frequently seen as a protective factor of stress, but self-report measures of mindfulness may overlap with other related constructs, such as mental health, and could thus not only be a predictor, but also an outcome of stress. This study thus aimed to examine the longitudinal bidirectional associations between the use and perceived helpfulness of the four mindfulness facets Observe, Describe, Nonjudge, and Nonreact with daily perceived stress. 

**Methods:** Participants from a large (N = 1276) mixed student and community group sample filled out a brief daily diary over the time span of seven days. Bidirectional cross-lagged effects were investigated using the random-intercept cross-lagged panel model, an extension of the traditional cross-lagged panel model that allows to differentiate between stable between-unit differences and time-varying within-unit dynamics. In addition, we controlled for several baseline and sociodemographic confounders.

**Results:** At the within-subject level, the use of Actaware was associated with higher perceived stress on the next day (β = .03, p = .029). The use (β = -.04, p = .025) and perceived helpfulness (β = -.05, p = .014) of Nonreact were associated with lower perceived stress on the next day. In turn, perceived stress was associated with lower perceived helpfulness of Describe (β = -.04, p = .037) and Nonreact (β = -.03, p = .038) on the next day. In addition, there were several residual correlations between mindfulness facets and perceived stress within days. At the between-subject level, there was a positive association between the random intercept of Describe and daily stress (r = .15, p = .003). In addition, while baseline perceived stress was negatively associated with the random intercepts of the mindfulness facets, two baseline components of mindfulness were not associated with the random intercept of perceived stress. 

**Conclusion:** Our results challenge prior results and assumptions regarding mindfulness as a buffering and protective factor against daily stress. With the exception of Nonreact, mindfulness was either positively associated with perceived stress, or in turn perceived stress appeared to interfere with the ability to stay mindful in daily life. 
:::


----

## [Differential associations of the two higher-order factors of mindfulness with trait empathy and the mediating role of emotional awareness](https://www.nature.com/articles/s41598-023-30323-6)

**Reference:** Borghi, O., Mayrhofer, L., Voracek, M. et al. Differential associations of the two higher-order factors of mindfulness with trait empathy and the mediating role of emotional awareness. Sci Rep 13, 3201 (2023). https://doi.org/10.1038/s41598-023-30323-

**Open data & code:** [Link to OSF](https://osf.io/ujp3e/)

::: {.callout-note}
## Abstract

Empathy enables us to understand the emotions of others and is an important determinant of prosocial behavior. Investigating the relationship between mindfulness and empathy could therefore provide important insights into factors that promote interpersonal understanding and pathways that contribute to prosocial behavior. As prior studies have yielded only inconsistent results, this study extended previous findings and investigated for the first time the associations of two important factors of mindfulness (Self-regulated Attention [SRA] and Orientation to Experience [OTE]) with two commonly proposed components of empathy (cognitive empathy and affective empathy). Using a community sample of N = 552 German-speaking adults, the two mindfulness factors were differentially associated with cognitive and affective empathy. SRA correlated positively with cognitive empathy (r = 0.44; OTE: r = 0.09), but OTE correlated negatively with affective empathy (r = −0.27; SRA: r = 0.11). This negative association was strongest for one specific aspect of affective empathy, emotional contagion. Revisiting previously reported mediating effects of emotion regulation, we found that emotional awareness mediated the associations with both components of empathy, but only for SRA. Together, these findings imply that mindfulness benefits the cognitive understanding of others’ emotions via two distinct pathways: by promoting emotional awareness (SRA) and by limiting the undue impact of others’ emotions on oneself (OTE).
:::


----

```{=html}
<div  style="margin: 30px; text-align: center;">
<a class="btn btn-primary" href="https://www.marvinschmitt.com/blog/website-tutorial-quarto/" role="button" target="_blank" style="padding: 15px 30px;">View the tutorial for this template (+ download link)</a>
</div>
```